def init(data_path: str) -> None: ...


class GameObject:
    def compare(self, steps: int | None) -> bool: ...

    def tap(self, steps: int | None, repeat: int | None) -> None: ...


def get_object(name: str) -> GameObject: ...
