from typing import Literal, cast

from screen_objects import ScreenObject, get_objects

from .paths import SAMPLES_DIR, REGIONS_DIR


ScreenObjectNames = Literal[
    "claim_daily",
    "blur",
    "x",
    "claim_healed",
    "hospital",
    "heal",
    "confirm_rss",
    "ask_help",
    "hospital_building",
    "speed_up",
    "one-tap_speed_up",
    "confirm_speed_up",
    "sanctuary",
    "claim_holy_water",
    "confirm_claim_water",
    "holy_quest",
    "claim_holy_quest",
    "holy_revival",
    "revive",
    "lord",
    "recall_all",
    "harvest",
    "gather_speed_up",
    "use",
    "tasks",
    "build_task",
    "hand",
    "upgrade",
    "upgrade_blue",
    "go_upgrade",
    "recruit_task",
    "recruit",
    "cavalry",
    "previous",
    "second",
    "recruit_blue",
    "horse",
    "claim",
    "map",
    "search",
    "food",
    "wood",
    "stone",
    "iron",
    "plus",
    "minus",
    "food_type",
    "wood_type",
    "stone_type",
    "iron_type",
    "go",
    "city_15",
    "city_19",
    "gather",
    "set_out",
    "book",
    "elite_mines",
    "blue",
    "check",
    "gather_elite",

    "leo",
    "haac",
    "hac",
    "VIChac",
    'farm,hacen',
    "kazuru_farm5",
    "kazuru_farm6",

    "avatar",
    "account",
    "switch",
    "login",
    "gmail",
    "acc_list",
    "green_castle",
    "castle",
    "confirm",
]



objects: dict[ScreenObjectNames, ScreenObject] = cast(
    dict[ScreenObjectNames, ScreenObject],
    get_objects(SAMPLES_DIR, REGIONS_DIR)
)
